### ISSUE TITLE
Add tab-completer for sub-commands

### ISSUE THREAD

**Issue by SrBedrock** [funkemunky/AntiVPN#10]
When writing commands in the chat, suggest sub-commands.

**Comment by funkemunky** [comment]
I believe this is already implemented.

**Comment by SrBedrock** [comment]
@funkemunky Subcommands are not suggested:
/antivpn **lookup** \<player>
/antivpn **alerts**
/antivpn **allowlist <add/remove>** <player/uuid/ip>
