### ISSUE TITLE
[BUG] Antivirus False Positive

### ISSUE THREAD

**Issue by Cartrigger** [funkemunky/AntiVPN#53]
**Describe the bug**
Using many antiviruses, it throws a false positive when server is loaded

**To Reproduce**
Start server

**Expected behavior**
To not false positive

**Screenshots**

**What instance are you running KauriVPN on?**
*Put an 'x' in the brackets to check it*
- [x] Velocity
- [x] Bukkit/Spigot
- [ ] Bungeecord

**Additional context**

https://www.virustotal.com/gui/file/b8a0356837f58fe39bb808fb007eeba0978fd0455842d14077850e876a45308a

**Comment by funkemunky** [comment]
This has been corrected with the latest pull request https://github.com/funkemunky/AntiVPN/pull/56
